version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - misspell
    - gocritic

  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true

formatters:
  enable:
    - goimports

issues:
  exclude-dirs:
    - vendor
